language: Python
python:
 - "3.7.4"
before install:
 - pip3 install --upgrade pip
 - choco install python --version 3.7.4
 - pip3 install -U pytest
 - pip3 install spotipy
 - pip3 install git+https://github.com/plamere/spotipy.git --upgrade
 - pip3 install Pillow
env: 
 - DJANGO_VERSION=2.2.6
script: 
 - python hello/test_pytest.py

