language: Python
python:
 - "3.7.4"
env: 
 - DJANGO_VERSION=3.7.0
before install:
 - pip3 install --upgrade pip
 - choco install python --version 3.7.4
 - choco install spotipy
 - pip3 install -U pytest
 - choco install git+https://github.com/plamere/spotipy.git --upgrade
 - pip3 install Pillow
script: 
 - python hello/test_pytest.py

