language: Python
python:
 - "3.7.4"
before install:
 - pip3 install --upgrade pip
 - choco install python --version 3.7.4
 - pip install -U pytest
env: 
 - DJANGO_VERSION=2.2.6
script: 
 - python3 test_pytest.py || python test_pytest.py

