language: Python
python:
 - "3.7.4"
before install:
 - pip3 install --upgrade pip
 - choco install python --version 3.7.4
 - python3 -m pip install -U pytest
 - python3 -m pip install spotipy
 - python3 -m pip install git+https://github.com/plamere/spotipy.git --upgrade
 - python3 -m pip install Pillow
env: 
 - DJANGO_VERSION=2.2.6
script: 
 - python test_pytest.py

