language: Python
python:
 - "3.7.4"
env: 
 - DJANGO_VERSION=3.7.0
before install:
 - pip install -U pytest
 - pip3 install --upgrade pip
 - choco install python --version 3.7.4
 - pip3 install Pillow
install:
 - pip install spotipy
script: 
 - pytest -v hello/test_pytest.py

